# a.08.92.misc.sh
#
echo "....."
echo "."
echo "."
echo "miscellaneous - for downloading files"
echo "."
echo "."
echo "Read the following:"
echo "."
echo "."
echo "."
echo "."
echo "https://www.linuxfromscratch.org/blfs/view/12.1/basicnet/lynx.html"
echo "."
echo "https://www.linuxfromscratch.org/blfs/view/12.1/general/gpm.html"
echo "."
echo "https://www.linuxfromscratch.org/blfs/view/12.1/postlfs/openssh.html"
echo "."
echo "https://www.linuxfromscratch.org/blfs/view/12.1/postlfs/sudo.html"
echo "."
#     Possible conflict with elogind
#echo "https://www.linuxfromscratch.org/blfs/view/12.1/general/acpid.html"
#echo "."
echo "."
echo "."
echo "Needed additional downloads"
echo "."
echo "."
echo "https://invisible-mirror.net/archives/lynx/tarballs/lynx2.8.9rel.1.tar.bz2"
echo "https://www.linuxfromscratch.org/patches/blfs/12.1/lynx-2.8.9rel.1-security_fix-1.patch"
echo "."
echo "https://anduin.linuxfromscratch.org/BLFS/gpm/gpm-1.20.7.tar.bz2"
echo "https://www.linuxfromscratch.org/patches/blfs/12.1/gpm-1.20.7-consolidated-1.patch"
echo "."
echo "https://ftp.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-9.6p1.tar.gz"
echo "."
echo "https://www.sudo.ws/dist/sudo-1.9.15p5.tar.gz"
echo "."
#     Possible conflict with elogind
#echo "https://downloads.sourceforge.net/acpid2/acpid-2.0.34.tar.xz"
#echo "."
echo "."
echo "."
echo "....."
