# a.08.94.Linux-PAM.sh
#
echo "....."
echo "."
echo "."
echo "Linux-PAM is needed by BLFS apps"
echo "Shadow needs to be reBuild"
echo "."
echo "."
echo "Read the following:"
echo "."
echo "."
echo "."
echo "."
echo "https://www.linuxfromscratch.org/blfs/view/12.2/postlfs/linux-pam.html"
echo "https://www.linuxfromscratch.org/blfs/view/12.2/postlfs/shadow.html"
echo "."
echo "Needed additional downloads"
echo "."
echo "."
echo "https://github.com/linux-pam/linux-pam/releases/download/v1.6.1/Linux-PAM-1.6.1.tar.xz"
echo "https://github.com/linux-pam/linux-pam/releases/download/v1.6.1/Linux-PAM-1.6.1-docs.tar.xz"
echo "https://downloads.sourceforge.net/libtirpc/libtirpc-1.3.5.tar.bz2"
echo "."
echo "."
echo "....."
