# a.08.92.NTP.sh
#
echo "....."
echo "."
echo "."
echo "Network Time Protocol to sync clocks"
echo "."
echo "."
echo "Read the following:"
echo "."
echo "."
echo "."
echo "."
echo "https://www.linuxfromscratch.org/blfs/view/12.2/basicnet/ntp.html"
echo "."
echo "."
echo "."
echo "Needed additional downloads"
echo "."
echo "."
echo "https://www.eecis.udel.edu/~ntp/ntp_spool/ntp4/ntp-4.2/ntp-4.2.8p18.tar.gz"
echo "https://www.cpan.org/authors/id/S/SU/SULLR/IO-Socket-SSL-2.088.tar.gz"
echo "https://cpan.metacpan.org/authors/id/C/CH/CHRISN/Net-SSLeay-1.94.tar.gz"
echo "."
echo "."
echo "."
echo "....."
