# a.08.91.WGet.sh
#
echo "....."
echo "."
echo "."
echo "WGet - for downloading files"
echo "."
echo "."
echo "Read the following:"
echo "."
echo "."
echo "."
echo "."
echo "https://www.linuxfromscratch.org/blfs/view/12.2/general/libtasn1.html"
echo "https://www.linuxfromscratch.org/blfs/view/12.2/postlfs/p11-kit.html"
echo "https://www.linuxfromscratch.org/blfs/view/12.2/postlfs/make-ca.html"
echo "https://www.linuxfromscratch.org/blfs/view/12.2/basicnet/wget.html"
echo "."
echo "."
echo "."
echo "Needed additional downloads"
echo "."
echo "."
echo "https://ftp.gnu.org/gnu/libtasn1/libtasn1-4.19.0.tar.gz"
echo "https://github.com/p11-glue/p11-kit/releases/download/0.25.5/p11-kit-0.25.5.tar.xz"
echo "https://github.com/lfs-book/make-ca/archive/v1.14/make-ca-1.14.tar.gz"
echo "https://ftp.gnu.org/gnu/wget/wget-1.24.5.tar.gz"
echo "."
echo "."
echo "."
echo "....."
