# a.08.92.misc.sh
#
echo "....."
echo "."
echo "."
echo "miscellaneous apps"
echo "."
echo "."
echo "Read the following:"
echo "."
echo "."
echo "."
echo "."
echo "https://www.linuxfromscratch.org/blfs/view/12.2/basicnet/lynx.html"
echo "."
echo "https://www.linuxfromscratch.org/blfs/view/12.2/general/gpm.html"
echo "."
echo "https://www.linuxfromscratch.org/blfs/view/12.2/postlfs/openssh.html"
echo "."
echo "https://www.linuxfromscratch.org/blfs/view/12.2/postlfs/sudo.html"
echo "."
echo "https://www.linuxfromscratch.org/blfs/view/12.2/general/which.html"
echo "."
echo "https://www.linuxfromscratch.org/blfs/view/12.2/general/pciutils.html"
echo "."
echo "https://www.linuxfromscratch.org/blfs/view/12.2/general/hwdata.html"
echo "."
echo "search sshpass"
echo "."
#     Possible conflict with elogind
#echo "https://www.linuxfromscratch.org/blfs/view/12.2/general/acpid.html"
#echo "."
echo "."
echo "."
echo "Needed additional downloads"
echo "."
echo "."
echo "https://invisible-mirror.net/archives/lynx/tarballs/lynx2.9.2.tar.bz2"
echo "."
echo "https://anduin.linuxfromscratch.org/BLFS/gpm/gpm-1.20.7.tar.bz2"
echo "https://www.linuxfromscratch.org/patches/blfs/12.2/gpm-1.20.7-consolidated-1.patch"
echo "."
echo "https://ftp.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-9.8p1.tar.gz"
echo "."
echo "https://www.sudo.ws/dist/sudo-1.9.15p5.tar.gz"
echo "."
echo "https://ftp.gnu.org/gnu/which/which-2.21.tar.gz"
echo "."
echo "https://mj.ucw.cz/download/linux/pci/pciutils-3.13.0.tar.gz"
echo "."
echo "https://github.com/vcrhonek/hwdata/archive/v0.385/hwdata-0.385.tar.gz"
echo "."
echo "https://sourceforge.net/projects/sshpass/files/sshpass/1.10/sshpass-1.10.tar.gz"
echo "."
#     Possible conflict with elogind
#echo "https://downloads.sourceforge.net/acpid2/acpid-2.0.34.tar.xz"
#echo "."
echo "."
echo "."
echo "....."
