# a.08.90.GRUB-2.12.for.EFI.x64.sh
#
# replacement for 8.63 GRUB for BIOS
#
echo "....."
echo "."
echo "."
echo "GRUB for EFI x64"
echo "."
echo "."
echo "Read the following:"
echo "."
echo "."
echo "."
echo "."
echo "https://www.linuxfromscratch.org/blfs/view/12.1/general/popt.html"
echo "."
echo "https://www.linuxfromscratch.org/blfs/view/12.1/general/mandoc.html"
echo "https://www.linuxfromscratch.org/blfs/view/12.1/postlfs/efivar.html"
echo "."
echo "https://www.linuxfromscratch.org/blfs/view/12.1/postlfs/efibootmgr.html"
echo "."
echo "https://www.linuxfromscratch.org/blfs/view/12.1/postlfs/grub-efi.html"
echo "."
echo "."
echo "."
echo "Needed additional downloads"
echo "."
echo "."
echo "http://ftp.rpm.org/popt/releases/popt-1.x/popt-1.19.tar.gz"
echo "."
echo "https://mandoc.bsd.lv/snapshots/mandoc-1.14.6.tar.gz"
echo "https://github.com/rhboot/efivar/archive/39/efivar-39.tar.gz"
echo "."
echo "https://github.com/rhboot/efibootmgr/archive/18/efibootmgr-18.tar.gz"
echo "."
echo "https://unifoundry.com/pub/unifont/unifont-15.1.04/font-builds/unifont-15.1.04.pcf.gz"
echo "https://ftp.gnu.org/gnu/grub/grub-2.12.tar.xz"
echo "."
echo "."
echo "."
echo "....."
