# a.08.93.NTP.sh
#
echo "....."
echo "."
echo "."
echo "Network Time Protocol to sync clocks"
echo "."
echo "."
echo "Read the following:"
echo "."
echo "."
echo "."
echo "."
echo "https://www.linuxfromscratch.org/blfs/view/12.3/basicnet/ntp.html"
echo "https://www.linuxfromscratch.org/blfs/view/12.3/general/perl-modules.html#perl-io-socket-ssl"
echo "https://www.linuxfromscratch.org/blfs/view/12.3/general/perl-deps.html#perl-net-ssleay"
echo "."
echo "."
echo "."
echo "Needed additional downloads"
echo "."
echo "."
echo "https://www.eecis.udel.edu/~ntp/ntp_spool/ntp4/ntp-4.2/ntp-4.2.8p18.tar.gz"
echo "https://www.cpan.org/authors/id/S/SU/SULLR/IO-Socket-SSL-2.089.tar.gz"
echo "https://cpan.metacpan.org/authors/id/C/CH/CHRISN/Net-SSLeay-1.94.tar.gz"
echo "."
echo "."
echo "."
echo "....."
