# a.08.94.Linux-PAM.sh
#
echo "....."
echo "."
echo "."
echo "Linux-PAM is needed by BLFS apps"
echo "Shadow needs to be reBuild"
echo "."
echo "."
echo "Read the following:"
echo "."
echo "."
echo "."
echo "."
echo "https://www.linuxfromscratch.org/blfs/view/12.3/basicnet/libtirpc.html"
echo "https://www.linuxfromscratch.org/blfs/view/12.3/postlfs/linux-pam.html"
echo "https://www.linuxfromscratch.org/blfs/view/12.3/postlfs/shadow.html"
echo "."
echo "Needed additional downloads"
echo "."
echo "."
echo "https://github.com/linux-pam/linux-pam/releases/download/v1.7.0/Linux-PAM-1.7.0.tar.xz"
echo "https://anduin.linuxfromscratch.org/BLFS/Linux-PAM/Linux-PAM-1.7.0-docs.tar.xz"
echo "https://downloads.sourceforge.net/libtirpc/libtirpc-1.3.6.tar.bz2"
echo "."
echo "."
echo "....."
