# a.08.91.WGet.sh
#
echo "....."
echo "."
echo "."
echo "WGet - for downloading files"
echo "."
echo "."
echo "Read the following:"
echo "."
echo "."
echo "."
echo "."
echo "https://www.linuxfromscratch.org/blfs/view/12.3/general/nspr.html"
echo "https://www.linuxfromscratch.org/blfs/view/12.3/server/sqlite.html"
echo "https://www.linuxfromscratch.org/blfs/view/12.3/postlfs/nss.html"
echo "https://www.linuxfromscratch.org/blfs/view/12.3/general/libtasn1.html"
echo "https://www.linuxfromscratch.org/blfs/view/12.3/postlfs/p11-kit.html"
echo "https://www.linuxfromscratch.org/blfs/view/12.3/postlfs/make-ca.html"
echo "https://www.linuxfromscratch.org/blfs/view/12.3/general/libunistring.html"
echo "https://www.linuxfromscratch.org/blfs/view/12.3/general/libidn2.html"
echo "https://www.linuxfromscratch.org/blfs/view/12.3/basicnet/libpsl.html"
echo "https://www.linuxfromscratch.org/blfs/view/12.3/basicnet/wget.html"
echo "."
echo "."
echo "."
echo "Needed additional downloads"
echo "."
echo "."
echo "https://archive.mozilla.org/pub/nspr/releases/v4.36/src/nspr-4.36.tar.gz"
echo "https://sqlite.org/2025/sqlite-autoconf-3490100.tar.gz"
echo "https://sqlite.org/2025/sqlite-doc-3490100.zip"
echo "https://archive.mozilla.org/pub/security/nss/releases/NSS_3_108_RTM/src/nss-3.108.tar.gz"
echo "https://www.linuxfromscratch.org/patches/blfs/12.3/nss-standalone-1.patch"
echo "https://ftp.gnu.org/gnu/libtasn1/libtasn1-4.20.0.tar.gz"
echo "https://github.com/p11-glue/p11-kit/releases/download/0.25.5/p11-kit-0.25.5.tar.xz"
echo "https://github.com/lfs-book/make-ca/archive/v1.15/make-ca-1.15.tar.gz"
echo "https://ftp.gnu.org/gnu/libunistring/libunistring-1.3.tar.xz"
echo "https://ftp.gnu.org/gnu/libidn/libidn2-2.3.7.tar.gz"
echo "https://github.com/rockdaboot/libpsl/releases/download/0.21.5/libpsl-0.21.5.tar.gz"
echo "https://ftp.gnu.org/gnu/wget/wget-1.25.0.tar.gz"
echo "."
echo "."
echo "."
echo "....."
